# Generated by Django 4.2.1 on 2023-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=3)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
